/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteAllModerationHistory200,
  DeleteModerationLog200,
  HTTPValidationError,
  ListModerationHistoryParams,
  ListReportedCommentsParams,
  ModerationAction,
  ModerationLogResponse,
  PendingCountResponse,
  Recipe,
  RecipeDraftResponse,
  ReportedCommentResponse
} from '.././model';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Pending Count
 */
export const getPendingCount = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PendingCountResponse>(
      {url: `/api/v1/moderation/pending-count`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPendingCountQueryKey = () => {
    return [
    `/api/v1/moderation/pending-count`
    ] as const;
    }

    
export const getGetPendingCountQueryOptions = <TData = Awaited<ReturnType<typeof getPendingCount>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPendingCountQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPendingCount>>> = ({ signal }) => getPendingCount(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPendingCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPendingCountQueryResult = NonNullable<Awaited<ReturnType<typeof getPendingCount>>>
export type GetPendingCountQueryError = unknown


export function useGetPendingCount<TData = Awaited<ReturnType<typeof getPendingCount>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPendingCount>>,
          TError,
          Awaited<ReturnType<typeof getPendingCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPendingCount<TData = Awaited<ReturnType<typeof getPendingCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPendingCount>>,
          TError,
          Awaited<ReturnType<typeof getPendingCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPendingCount<TData = Awaited<ReturnType<typeof getPendingCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Pending Count
 */

export function useGetPendingCount<TData = Awaited<ReturnType<typeof getPendingCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPendingCountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List Moderation History
 */
export const listModerationHistory = (
    params?: ListModerationHistoryParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ModerationLogResponse[]>(
      {url: `/api/v1/moderation/history`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListModerationHistoryQueryKey = (params?: ListModerationHistoryParams,) => {
    return [
    `/api/v1/moderation/history`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListModerationHistoryQueryOptions = <TData = Awaited<ReturnType<typeof listModerationHistory>>, TError = HTTPValidationError>(params?: ListModerationHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listModerationHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListModerationHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listModerationHistory>>> = ({ signal }) => listModerationHistory(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listModerationHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListModerationHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof listModerationHistory>>>
export type ListModerationHistoryQueryError = HTTPValidationError


export function useListModerationHistory<TData = Awaited<ReturnType<typeof listModerationHistory>>, TError = HTTPValidationError>(
 params: undefined |  ListModerationHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listModerationHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listModerationHistory>>,
          TError,
          Awaited<ReturnType<typeof listModerationHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListModerationHistory<TData = Awaited<ReturnType<typeof listModerationHistory>>, TError = HTTPValidationError>(
 params?: ListModerationHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listModerationHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listModerationHistory>>,
          TError,
          Awaited<ReturnType<typeof listModerationHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListModerationHistory<TData = Awaited<ReturnType<typeof listModerationHistory>>, TError = HTTPValidationError>(
 params?: ListModerationHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listModerationHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Moderation History
 */

export function useListModerationHistory<TData = Awaited<ReturnType<typeof listModerationHistory>>, TError = HTTPValidationError>(
 params?: ListModerationHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listModerationHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListModerationHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Delete All Moderation History
 */
export const deleteAllModerationHistory = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteAllModerationHistory200>(
      {url: `/api/v1/moderation/history`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAllModerationHistoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllModerationHistory>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAllModerationHistory>>, TError,void, TContext> => {

const mutationKey = ['deleteAllModerationHistory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAllModerationHistory>>, void> = () => {
          

          return  deleteAllModerationHistory(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAllModerationHistoryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAllModerationHistory>>>
    
    export type DeleteAllModerationHistoryMutationError = unknown

    /**
 * @summary Delete All Moderation History
 */
export const useDeleteAllModerationHistory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllModerationHistory>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAllModerationHistory>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDeleteAllModerationHistoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Moderation Log
 */
export const deleteModerationLog = (
    logId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteModerationLog200>(
      {url: `/api/v1/moderation/history/${logId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteModerationLogMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModerationLog>>, TError,{logId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteModerationLog>>, TError,{logId: number}, TContext> => {

const mutationKey = ['deleteModerationLog'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteModerationLog>>, {logId: number}> = (props) => {
          const {logId} = props ?? {};

          return  deleteModerationLog(logId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteModerationLogMutationResult = NonNullable<Awaited<ReturnType<typeof deleteModerationLog>>>
    
    export type DeleteModerationLogMutationError = HTTPValidationError

    /**
 * @summary Delete Moderation Log
 */
export const useDeleteModerationLog = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModerationLog>>, TError,{logId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteModerationLog>>,
        TError,
        {logId: number},
        TContext
      > => {

      const mutationOptions = getDeleteModerationLogMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Pending Recipes
 */
export const listPendingRecipes = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Recipe[]>(
      {url: `/api/v1/moderation/recipes`, method: 'GET', signal
    },
      options);
    }
  



export const getListPendingRecipesQueryKey = () => {
    return [
    `/api/v1/moderation/recipes`
    ] as const;
    }

    
export const getListPendingRecipesQueryOptions = <TData = Awaited<ReturnType<typeof listPendingRecipes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPendingRecipesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPendingRecipes>>> = ({ signal }) => listPendingRecipes(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPendingRecipesQueryResult = NonNullable<Awaited<ReturnType<typeof listPendingRecipes>>>
export type ListPendingRecipesQueryError = unknown


export function useListPendingRecipes<TData = Awaited<ReturnType<typeof listPendingRecipes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPendingRecipes>>,
          TError,
          Awaited<ReturnType<typeof listPendingRecipes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPendingRecipes<TData = Awaited<ReturnType<typeof listPendingRecipes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPendingRecipes>>,
          TError,
          Awaited<ReturnType<typeof listPendingRecipes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPendingRecipes<TData = Awaited<ReturnType<typeof listPendingRecipes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Pending Recipes
 */

export function useListPendingRecipes<TData = Awaited<ReturnType<typeof listPendingRecipes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPendingRecipesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Moderate Recipe
 */
export const moderateRecipe = (
    recipeId: number,
    moderationAction: ModerationAction,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Recipe>(
      {url: `/api/v1/moderation/recipes/${recipeId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: moderationAction, signal
    },
      options);
    }
  


export const getModerateRecipeMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moderateRecipe>>, TError,{recipeId: number;data: ModerationAction}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof moderateRecipe>>, TError,{recipeId: number;data: ModerationAction}, TContext> => {

const mutationKey = ['moderateRecipe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moderateRecipe>>, {recipeId: number;data: ModerationAction}> = (props) => {
          const {recipeId,data} = props ?? {};

          return  moderateRecipe(recipeId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ModerateRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof moderateRecipe>>>
    export type ModerateRecipeMutationBody = ModerationAction
    export type ModerateRecipeMutationError = HTTPValidationError

    /**
 * @summary Moderate Recipe
 */
export const useModerateRecipe = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moderateRecipe>>, TError,{recipeId: number;data: ModerationAction}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moderateRecipe>>,
        TError,
        {recipeId: number;data: ModerationAction},
        TContext
      > => {

      const mutationOptions = getModerateRecipeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Pending Drafts
 */
export const listPendingDrafts = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RecipeDraftResponse[]>(
      {url: `/api/v1/moderation/drafts`, method: 'GET', signal
    },
      options);
    }
  



export const getListPendingDraftsQueryKey = () => {
    return [
    `/api/v1/moderation/drafts`
    ] as const;
    }

    
export const getListPendingDraftsQueryOptions = <TData = Awaited<ReturnType<typeof listPendingDrafts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPendingDraftsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPendingDrafts>>> = ({ signal }) => listPendingDrafts(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPendingDraftsQueryResult = NonNullable<Awaited<ReturnType<typeof listPendingDrafts>>>
export type ListPendingDraftsQueryError = unknown


export function useListPendingDrafts<TData = Awaited<ReturnType<typeof listPendingDrafts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPendingDrafts>>,
          TError,
          Awaited<ReturnType<typeof listPendingDrafts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPendingDrafts<TData = Awaited<ReturnType<typeof listPendingDrafts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPendingDrafts>>,
          TError,
          Awaited<ReturnType<typeof listPendingDrafts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPendingDrafts<TData = Awaited<ReturnType<typeof listPendingDrafts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Pending Drafts
 */

export function useListPendingDrafts<TData = Awaited<ReturnType<typeof listPendingDrafts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPendingDraftsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Moderate Draft
 */
export const moderateDraft = (
    draftId: number,
    moderationAction: ModerationAction,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RecipeDraftResponse>(
      {url: `/api/v1/moderation/drafts/${draftId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: moderationAction, signal
    },
      options);
    }
  


export const getModerateDraftMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moderateDraft>>, TError,{draftId: number;data: ModerationAction}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof moderateDraft>>, TError,{draftId: number;data: ModerationAction}, TContext> => {

const mutationKey = ['moderateDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moderateDraft>>, {draftId: number;data: ModerationAction}> = (props) => {
          const {draftId,data} = props ?? {};

          return  moderateDraft(draftId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ModerateDraftMutationResult = NonNullable<Awaited<ReturnType<typeof moderateDraft>>>
    export type ModerateDraftMutationBody = ModerationAction
    export type ModerateDraftMutationError = HTTPValidationError

    /**
 * @summary Moderate Draft
 */
export const useModerateDraft = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moderateDraft>>, TError,{draftId: number;data: ModerationAction}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moderateDraft>>,
        TError,
        {draftId: number;data: ModerationAction},
        TContext
      > => {

      const mutationOptions = getModerateDraftMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List comments with active reports for moderation.
 * @summary List Reported Comments
 */
export const listReportedComments = (
    params?: ListReportedCommentsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ReportedCommentResponse[]>(
      {url: `/api/v1/moderation/comments`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListReportedCommentsQueryKey = (params?: ListReportedCommentsParams,) => {
    return [
    `/api/v1/moderation/comments`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListReportedCommentsQueryOptions = <TData = Awaited<ReturnType<typeof listReportedComments>>, TError = HTTPValidationError>(params?: ListReportedCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReportedComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListReportedCommentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listReportedComments>>> = ({ signal }) => listReportedComments(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listReportedComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListReportedCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof listReportedComments>>>
export type ListReportedCommentsQueryError = HTTPValidationError


export function useListReportedComments<TData = Awaited<ReturnType<typeof listReportedComments>>, TError = HTTPValidationError>(
 params: undefined |  ListReportedCommentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReportedComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReportedComments>>,
          TError,
          Awaited<ReturnType<typeof listReportedComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReportedComments<TData = Awaited<ReturnType<typeof listReportedComments>>, TError = HTTPValidationError>(
 params?: ListReportedCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReportedComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReportedComments>>,
          TError,
          Awaited<ReturnType<typeof listReportedComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReportedComments<TData = Awaited<ReturnType<typeof listReportedComments>>, TError = HTTPValidationError>(
 params?: ListReportedCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReportedComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Reported Comments
 */

export function useListReportedComments<TData = Awaited<ReturnType<typeof listReportedComments>>, TError = HTTPValidationError>(
 params?: ListReportedCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReportedComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListReportedCommentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Dismiss all reports for a comment (keep comment, clear reports).
 * @summary Dismiss Comment Reports
 */
export const dismissCommentReports = (
    commentId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/moderation/comments/${commentId}/dismiss`, method: 'POST', signal
    },
      options);
    }
  


export const getDismissCommentReportsMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dismissCommentReports>>, TError,{commentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof dismissCommentReports>>, TError,{commentId: number}, TContext> => {

const mutationKey = ['dismissCommentReports'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dismissCommentReports>>, {commentId: number}> = (props) => {
          const {commentId} = props ?? {};

          return  dismissCommentReports(commentId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DismissCommentReportsMutationResult = NonNullable<Awaited<ReturnType<typeof dismissCommentReports>>>
    
    export type DismissCommentReportsMutationError = HTTPValidationError

    /**
 * @summary Dismiss Comment Reports
 */
export const useDismissCommentReports = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dismissCommentReports>>, TError,{commentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dismissCommentReports>>,
        TError,
        {commentId: number},
        TContext
      > => {

      const mutationOptions = getDismissCommentReportsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    