/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ModerationAction,
  Recipe,
  RecipeDraftResponse
} from '.././model';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Pending Recipes
 */
export const listPendingRecipes = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Recipe[]>(
      {url: `/api/v1/moderation/recipes`, method: 'GET', signal
    },
      options);
    }
  



export const getListPendingRecipesQueryKey = () => {
    return [
    `/api/v1/moderation/recipes`
    ] as const;
    }

    
export const getListPendingRecipesQueryOptions = <TData = Awaited<ReturnType<typeof listPendingRecipes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPendingRecipesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPendingRecipes>>> = ({ signal }) => listPendingRecipes(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPendingRecipesQueryResult = NonNullable<Awaited<ReturnType<typeof listPendingRecipes>>>
export type ListPendingRecipesQueryError = unknown


export function useListPendingRecipes<TData = Awaited<ReturnType<typeof listPendingRecipes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPendingRecipes>>,
          TError,
          Awaited<ReturnType<typeof listPendingRecipes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPendingRecipes<TData = Awaited<ReturnType<typeof listPendingRecipes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPendingRecipes>>,
          TError,
          Awaited<ReturnType<typeof listPendingRecipes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPendingRecipes<TData = Awaited<ReturnType<typeof listPendingRecipes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Pending Recipes
 */

export function useListPendingRecipes<TData = Awaited<ReturnType<typeof listPendingRecipes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingRecipes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPendingRecipesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Moderate Recipe
 */
export const moderateRecipe = (
    recipeId: number,
    moderationAction: ModerationAction,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Recipe>(
      {url: `/api/v1/moderation/recipes/${recipeId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: moderationAction, signal
    },
      options);
    }
  


export const getModerateRecipeMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moderateRecipe>>, TError,{recipeId: number;data: ModerationAction}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof moderateRecipe>>, TError,{recipeId: number;data: ModerationAction}, TContext> => {

const mutationKey = ['moderateRecipe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moderateRecipe>>, {recipeId: number;data: ModerationAction}> = (props) => {
          const {recipeId,data} = props ?? {};

          return  moderateRecipe(recipeId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ModerateRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof moderateRecipe>>>
    export type ModerateRecipeMutationBody = ModerationAction
    export type ModerateRecipeMutationError = HTTPValidationError

    /**
 * @summary Moderate Recipe
 */
export const useModerateRecipe = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moderateRecipe>>, TError,{recipeId: number;data: ModerationAction}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moderateRecipe>>,
        TError,
        {recipeId: number;data: ModerationAction},
        TContext
      > => {

      const mutationOptions = getModerateRecipeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Pending Drafts
 */
export const listPendingDrafts = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RecipeDraftResponse[]>(
      {url: `/api/v1/moderation/drafts`, method: 'GET', signal
    },
      options);
    }
  



export const getListPendingDraftsQueryKey = () => {
    return [
    `/api/v1/moderation/drafts`
    ] as const;
    }

    
export const getListPendingDraftsQueryOptions = <TData = Awaited<ReturnType<typeof listPendingDrafts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPendingDraftsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPendingDrafts>>> = ({ signal }) => listPendingDrafts(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPendingDraftsQueryResult = NonNullable<Awaited<ReturnType<typeof listPendingDrafts>>>
export type ListPendingDraftsQueryError = unknown


export function useListPendingDrafts<TData = Awaited<ReturnType<typeof listPendingDrafts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPendingDrafts>>,
          TError,
          Awaited<ReturnType<typeof listPendingDrafts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPendingDrafts<TData = Awaited<ReturnType<typeof listPendingDrafts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPendingDrafts>>,
          TError,
          Awaited<ReturnType<typeof listPendingDrafts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPendingDrafts<TData = Awaited<ReturnType<typeof listPendingDrafts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Pending Drafts
 */

export function useListPendingDrafts<TData = Awaited<ReturnType<typeof listPendingDrafts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPendingDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPendingDraftsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Moderate Draft
 */
export const moderateDraft = (
    draftId: number,
    moderationAction: ModerationAction,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RecipeDraftResponse>(
      {url: `/api/v1/moderation/drafts/${draftId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: moderationAction, signal
    },
      options);
    }
  


export const getModerateDraftMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moderateDraft>>, TError,{draftId: number;data: ModerationAction}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof moderateDraft>>, TError,{draftId: number;data: ModerationAction}, TContext> => {

const mutationKey = ['moderateDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moderateDraft>>, {draftId: number;data: ModerationAction}> = (props) => {
          const {draftId,data} = props ?? {};

          return  moderateDraft(draftId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ModerateDraftMutationResult = NonNullable<Awaited<ReturnType<typeof moderateDraft>>>
    export type ModerateDraftMutationBody = ModerationAction
    export type ModerateDraftMutationError = HTTPValidationError

    /**
 * @summary Moderate Draft
 */
export const useModerateDraft = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moderateDraft>>, TError,{draftId: number;data: ModerationAction}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moderateDraft>>,
        TError,
        {draftId: number;data: ModerationAction},
        TContext
      > => {

      const mutationOptions = getModerateDraftMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    