/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CheckFollowingParams,
  FollowCheckResponse,
  GetFollowersParams,
  GetFollowingParams,
  HTTPValidationError,
  PublicUserResponse
} from '.././model';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Idempotently follow a user. Returns updated target profile.
 * @summary Follow User
 */
export const followUser = (
    userId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PublicUserResponse>(
      {url: `/api/v1/follows/${userId}`, method: 'POST', signal
    },
      options);
    }
  


export const getFollowUserMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof followUser>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof followUser>>, TError,{userId: number}, TContext> => {

const mutationKey = ['followUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof followUser>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  followUser(userId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FollowUserMutationResult = NonNullable<Awaited<ReturnType<typeof followUser>>>
    
    export type FollowUserMutationError = HTTPValidationError

    /**
 * @summary Follow User
 */
export const useFollowUser = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof followUser>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof followUser>>,
        TError,
        {userId: number},
        TContext
      > => {

      const mutationOptions = getFollowUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Idempotently unfollow a user. Returns updated target profile.
 * @summary Unfollow User
 */
export const unfollowUser = (
    userId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PublicUserResponse>(
      {url: `/api/v1/follows/${userId}`, method: 'DELETE'
    },
      options);
    }
  


export const getUnfollowUserMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfollowUser>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof unfollowUser>>, TError,{userId: number}, TContext> => {

const mutationKey = ['unfollowUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unfollowUser>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  unfollowUser(userId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnfollowUserMutationResult = NonNullable<Awaited<ReturnType<typeof unfollowUser>>>
    
    export type UnfollowUserMutationError = HTTPValidationError

    /**
 * @summary Unfollow User
 */
export const useUnfollowUser = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfollowUser>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unfollowUser>>,
        TError,
        {userId: number},
        TContext
      > => {

      const mutationOptions = getUnfollowUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List followers of a user. Optional auth for is_following.
 * @summary Get Followers
 */
export const getFollowers = (
    userId: number,
    params?: GetFollowersParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PublicUserResponse[]>(
      {url: `/api/v1/follows/${userId}/followers`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetFollowersQueryKey = (userId?: number,
    params?: GetFollowersParams,) => {
    return [
    `/api/v1/follows/${userId}/followers`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetFollowersQueryOptions = <TData = Awaited<ReturnType<typeof getFollowers>>, TError = HTTPValidationError>(userId: number,
    params?: GetFollowersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFollowersQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFollowers>>> = ({ signal }) => getFollowers(userId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFollowersQueryResult = NonNullable<Awaited<ReturnType<typeof getFollowers>>>
export type GetFollowersQueryError = HTTPValidationError


export function useGetFollowers<TData = Awaited<ReturnType<typeof getFollowers>>, TError = HTTPValidationError>(
 userId: number,
    params: undefined |  GetFollowersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowers>>,
          TError,
          Awaited<ReturnType<typeof getFollowers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFollowers<TData = Awaited<ReturnType<typeof getFollowers>>, TError = HTTPValidationError>(
 userId: number,
    params?: GetFollowersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowers>>,
          TError,
          Awaited<ReturnType<typeof getFollowers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFollowers<TData = Awaited<ReturnType<typeof getFollowers>>, TError = HTTPValidationError>(
 userId: number,
    params?: GetFollowersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Followers
 */

export function useGetFollowers<TData = Awaited<ReturnType<typeof getFollowers>>, TError = HTTPValidationError>(
 userId: number,
    params?: GetFollowersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFollowersQueryOptions(userId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * List users that user_id follows. Optional auth for is_following.
 * @summary Get Following
 */
export const getFollowing = (
    userId: number,
    params?: GetFollowingParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PublicUserResponse[]>(
      {url: `/api/v1/follows/${userId}/following`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetFollowingQueryKey = (userId?: number,
    params?: GetFollowingParams,) => {
    return [
    `/api/v1/follows/${userId}/following`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetFollowingQueryOptions = <TData = Awaited<ReturnType<typeof getFollowing>>, TError = HTTPValidationError>(userId: number,
    params?: GetFollowingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFollowingQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFollowing>>> = ({ signal }) => getFollowing(userId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFollowingQueryResult = NonNullable<Awaited<ReturnType<typeof getFollowing>>>
export type GetFollowingQueryError = HTTPValidationError


export function useGetFollowing<TData = Awaited<ReturnType<typeof getFollowing>>, TError = HTTPValidationError>(
 userId: number,
    params: undefined |  GetFollowingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowing>>,
          TError,
          Awaited<ReturnType<typeof getFollowing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFollowing<TData = Awaited<ReturnType<typeof getFollowing>>, TError = HTTPValidationError>(
 userId: number,
    params?: GetFollowingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowing>>,
          TError,
          Awaited<ReturnType<typeof getFollowing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFollowing<TData = Awaited<ReturnType<typeof getFollowing>>, TError = HTTPValidationError>(
 userId: number,
    params?: GetFollowingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Following
 */

export function useGetFollowing<TData = Awaited<ReturnType<typeof getFollowing>>, TError = HTTPValidationError>(
 userId: number,
    params?: GetFollowingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFollowingQueryOptions(userId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Batch check which of the given user IDs the current user follows.
 * @summary Check Following
 */
export const checkFollowing = (
    params: CheckFollowingParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<FollowCheckResponse>(
      {url: `/api/v1/follows/check`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getCheckFollowingQueryKey = (params?: CheckFollowingParams,) => {
    return [
    `/api/v1/follows/check`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCheckFollowingQueryOptions = <TData = Awaited<ReturnType<typeof checkFollowing>>, TError = HTTPValidationError>(params: CheckFollowingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkFollowing>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckFollowingQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkFollowing>>> = ({ signal }) => checkFollowing(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof checkFollowing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckFollowingQueryResult = NonNullable<Awaited<ReturnType<typeof checkFollowing>>>
export type CheckFollowingQueryError = HTTPValidationError


export function useCheckFollowing<TData = Awaited<ReturnType<typeof checkFollowing>>, TError = HTTPValidationError>(
 params: CheckFollowingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkFollowing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkFollowing>>,
          TError,
          Awaited<ReturnType<typeof checkFollowing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckFollowing<TData = Awaited<ReturnType<typeof checkFollowing>>, TError = HTTPValidationError>(
 params: CheckFollowingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkFollowing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkFollowing>>,
          TError,
          Awaited<ReturnType<typeof checkFollowing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckFollowing<TData = Awaited<ReturnType<typeof checkFollowing>>, TError = HTTPValidationError>(
 params: CheckFollowingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkFollowing>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Check Following
 */

export function useCheckFollowing<TData = Awaited<ReturnType<typeof checkFollowing>>, TError = HTTPValidationError>(
 params: CheckFollowingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkFollowing>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCheckFollowingQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




