/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommentCreate,
  CommentReportCreate,
  CommentResponse,
  HTTPValidationError,
  ListRecipeCommentsParams
} from '.././model';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List top-level comments with their replies for a recipe.
 * @summary List Comments
 */
export const listRecipeComments = (
    recipeId: number,
    params?: ListRecipeCommentsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CommentResponse[]>(
      {url: `/api/v1/comments/${recipeId}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListRecipeCommentsQueryKey = (recipeId?: number,
    params?: ListRecipeCommentsParams,) => {
    return [
    `/api/v1/comments/${recipeId}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListRecipeCommentsQueryOptions = <TData = Awaited<ReturnType<typeof listRecipeComments>>, TError = HTTPValidationError>(recipeId: number,
    params?: ListRecipeCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipeComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRecipeCommentsQueryKey(recipeId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecipeComments>>> = ({ signal }) => listRecipeComments(recipeId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(recipeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRecipeComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRecipeCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof listRecipeComments>>>
export type ListRecipeCommentsQueryError = HTTPValidationError


export function useListRecipeComments<TData = Awaited<ReturnType<typeof listRecipeComments>>, TError = HTTPValidationError>(
 recipeId: number,
    params: undefined |  ListRecipeCommentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipeComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRecipeComments>>,
          TError,
          Awaited<ReturnType<typeof listRecipeComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRecipeComments<TData = Awaited<ReturnType<typeof listRecipeComments>>, TError = HTTPValidationError>(
 recipeId: number,
    params?: ListRecipeCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipeComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRecipeComments>>,
          TError,
          Awaited<ReturnType<typeof listRecipeComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRecipeComments<TData = Awaited<ReturnType<typeof listRecipeComments>>, TError = HTTPValidationError>(
 recipeId: number,
    params?: ListRecipeCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipeComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Comments
 */

export function useListRecipeComments<TData = Awaited<ReturnType<typeof listRecipeComments>>, TError = HTTPValidationError>(
 recipeId: number,
    params?: ListRecipeCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecipeComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRecipeCommentsQueryOptions(recipeId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Post a comment or reply on a recipe.
 * @summary Create Comment
 */
export const createRecipeComment = (
    recipeId: number,
    commentCreate: CommentCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CommentResponse>(
      {url: `/api/v1/comments/${recipeId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commentCreate, signal
    },
      options);
    }
  


export const getCreateRecipeCommentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipeComment>>, TError,{recipeId: number;data: CommentCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createRecipeComment>>, TError,{recipeId: number;data: CommentCreate}, TContext> => {

const mutationKey = ['createRecipeComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRecipeComment>>, {recipeId: number;data: CommentCreate}> = (props) => {
          const {recipeId,data} = props ?? {};

          return  createRecipeComment(recipeId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRecipeCommentMutationResult = NonNullable<Awaited<ReturnType<typeof createRecipeComment>>>
    export type CreateRecipeCommentMutationBody = CommentCreate
    export type CreateRecipeCommentMutationError = HTTPValidationError

    /**
 * @summary Create Comment
 */
export const useCreateRecipeComment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipeComment>>, TError,{recipeId: number;data: CommentCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRecipeComment>>,
        TError,
        {recipeId: number;data: CommentCreate},
        TContext
      > => {

      const mutationOptions = getCreateRecipeCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Soft-delete a comment (owner or moderator/admin only).
 * @summary Delete Comment
 */
export const deleteRecipeComment = (
    commentId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/comments/${commentId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteRecipeCommentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeComment>>, TError,{commentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeComment>>, TError,{commentId: number}, TContext> => {

const mutationKey = ['deleteRecipeComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRecipeComment>>, {commentId: number}> = (props) => {
          const {commentId} = props ?? {};

          return  deleteRecipeComment(commentId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRecipeCommentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRecipeComment>>>
    
    export type DeleteRecipeCommentMutationError = HTTPValidationError

    /**
 * @summary Delete Comment
 */
export const useDeleteRecipeComment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeComment>>, TError,{commentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRecipeComment>>,
        TError,
        {commentId: number},
        TContext
      > => {

      const mutationOptions = getDeleteRecipeCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Report a comment as abusive or spam. Notifies moderators.
 * @summary Report Comment
 */
export const reportRecipeComment = (
    commentId: number,
    commentReportCreate: CommentReportCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/comments/${commentId}/report`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commentReportCreate, signal
    },
      options);
    }
  


export const getReportRecipeCommentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportRecipeComment>>, TError,{commentId: number;data: CommentReportCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof reportRecipeComment>>, TError,{commentId: number;data: CommentReportCreate}, TContext> => {

const mutationKey = ['reportRecipeComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reportRecipeComment>>, {commentId: number;data: CommentReportCreate}> = (props) => {
          const {commentId,data} = props ?? {};

          return  reportRecipeComment(commentId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReportRecipeCommentMutationResult = NonNullable<Awaited<ReturnType<typeof reportRecipeComment>>>
    export type ReportRecipeCommentMutationBody = CommentReportCreate
    export type ReportRecipeCommentMutationError = HTTPValidationError

    /**
 * @summary Report Comment
 */
export const useReportRecipeComment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportRecipeComment>>, TError,{commentId: number;data: CommentReportCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reportRecipeComment>>,
        TError,
        {commentId: number;data: CommentReportCreate},
        TContext
      > => {

      const mutationOptions = getReportRecipeCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    