/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CheckFavoritesParams,
  FavoritesCheckResponse,
  HTTPValidationError,
  ReadMyFavoritesParams,
  Recipe
} from '.././model';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Idempotently mark the recipe as favorited by the current user.
 * @summary Favorite Recipe
 */
export const favoriteRecipe = (
    recipeId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Recipe>(
      {url: `/api/v1/favorites/${recipeId}`, method: 'POST', signal
    },
      options);
    }
  


export const getFavoriteRecipeMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof favoriteRecipe>>, TError,{recipeId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof favoriteRecipe>>, TError,{recipeId: number}, TContext> => {

const mutationKey = ['favoriteRecipe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof favoriteRecipe>>, {recipeId: number}> = (props) => {
          const {recipeId} = props ?? {};

          return  favoriteRecipe(recipeId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FavoriteRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof favoriteRecipe>>>
    
    export type FavoriteRecipeMutationError = HTTPValidationError

    /**
 * @summary Favorite Recipe
 */
export const useFavoriteRecipe = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof favoriteRecipe>>, TError,{recipeId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof favoriteRecipe>>,
        TError,
        {recipeId: number},
        TContext
      > => {

      const mutationOptions = getFavoriteRecipeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Idempotently remove the favorite link.
 * @summary Unfavorite Recipe
 */
export const unfavoriteRecipe = (
    recipeId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Recipe>(
      {url: `/api/v1/favorites/${recipeId}`, method: 'DELETE'
    },
      options);
    }
  


export const getUnfavoriteRecipeMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfavoriteRecipe>>, TError,{recipeId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof unfavoriteRecipe>>, TError,{recipeId: number}, TContext> => {

const mutationKey = ['unfavoriteRecipe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unfavoriteRecipe>>, {recipeId: number}> = (props) => {
          const {recipeId} = props ?? {};

          return  unfavoriteRecipe(recipeId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnfavoriteRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof unfavoriteRecipe>>>
    
    export type UnfavoriteRecipeMutationError = HTTPValidationError

    /**
 * @summary Unfavorite Recipe
 */
export const useUnfavoriteRecipe = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfavoriteRecipe>>, TError,{recipeId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unfavoriteRecipe>>,
        TError,
        {recipeId: number},
        TContext
      > => {

      const mutationOptions = getUnfavoriteRecipeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Return the current user's favorited (approved-only) recipes.
 * @summary Read My Favorites
 */
export const readMyFavorites = (
    params?: ReadMyFavoritesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Recipe[]>(
      {url: `/api/v1/favorites/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getReadMyFavoritesQueryKey = (params?: ReadMyFavoritesParams,) => {
    return [
    `/api/v1/favorites/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getReadMyFavoritesQueryOptions = <TData = Awaited<ReturnType<typeof readMyFavorites>>, TError = HTTPValidationError>(params?: ReadMyFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readMyFavorites>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadMyFavoritesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof readMyFavorites>>> = ({ signal }) => readMyFavorites(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readMyFavorites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadMyFavoritesQueryResult = NonNullable<Awaited<ReturnType<typeof readMyFavorites>>>
export type ReadMyFavoritesQueryError = HTTPValidationError


export function useReadMyFavorites<TData = Awaited<ReturnType<typeof readMyFavorites>>, TError = HTTPValidationError>(
 params: undefined |  ReadMyFavoritesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readMyFavorites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readMyFavorites>>,
          TError,
          Awaited<ReturnType<typeof readMyFavorites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadMyFavorites<TData = Awaited<ReturnType<typeof readMyFavorites>>, TError = HTTPValidationError>(
 params?: ReadMyFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readMyFavorites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readMyFavorites>>,
          TError,
          Awaited<ReturnType<typeof readMyFavorites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadMyFavorites<TData = Awaited<ReturnType<typeof readMyFavorites>>, TError = HTTPValidationError>(
 params?: ReadMyFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readMyFavorites>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read My Favorites
 */

export function useReadMyFavorites<TData = Awaited<ReturnType<typeof readMyFavorites>>, TError = HTTPValidationError>(
 params?: ReadMyFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readMyFavorites>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadMyFavoritesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Lightweight overlay endpoint: which of the given recipes are
favorited by the current user.

Designed for the homepage category shelves, where the recipe list is
served from a shared (user-agnostic) Redis cache and so cannot carry
``is_favorited`` directly. The client batches this call once per
shelves-page render to paint the heart-toggle state correctly.
 * @summary Check Favorites
 */
export const checkFavorites = (
    params: CheckFavoritesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<FavoritesCheckResponse>(
      {url: `/api/v1/favorites/check`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getCheckFavoritesQueryKey = (params?: CheckFavoritesParams,) => {
    return [
    `/api/v1/favorites/check`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCheckFavoritesQueryOptions = <TData = Awaited<ReturnType<typeof checkFavorites>>, TError = HTTPValidationError>(params: CheckFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkFavorites>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckFavoritesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkFavorites>>> = ({ signal }) => checkFavorites(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof checkFavorites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckFavoritesQueryResult = NonNullable<Awaited<ReturnType<typeof checkFavorites>>>
export type CheckFavoritesQueryError = HTTPValidationError


export function useCheckFavorites<TData = Awaited<ReturnType<typeof checkFavorites>>, TError = HTTPValidationError>(
 params: CheckFavoritesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkFavorites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkFavorites>>,
          TError,
          Awaited<ReturnType<typeof checkFavorites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckFavorites<TData = Awaited<ReturnType<typeof checkFavorites>>, TError = HTTPValidationError>(
 params: CheckFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkFavorites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkFavorites>>,
          TError,
          Awaited<ReturnType<typeof checkFavorites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckFavorites<TData = Awaited<ReturnType<typeof checkFavorites>>, TError = HTTPValidationError>(
 params: CheckFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkFavorites>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Check Favorites
 */

export function useCheckFavorites<TData = Awaited<ReturnType<typeof checkFavorites>>, TError = HTTPValidationError>(
 params: CheckFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkFavorites>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCheckFavoritesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




