/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMyRecipeRating200,
  HTTPValidationError,
  RatingCreate,
  Recipe
} from '.././model';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create or update the current user's star rating for a recipe.
 * @summary Upsert Rating
 */
export const upsertRecipeRating = (
    recipeId: number,
    ratingCreate: RatingCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Recipe>(
      {url: `/api/v1/ratings/${recipeId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ratingCreate, signal
    },
      options);
    }
  


export const getUpsertRecipeRatingMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertRecipeRating>>, TError,{recipeId: number;data: RatingCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertRecipeRating>>, TError,{recipeId: number;data: RatingCreate}, TContext> => {

const mutationKey = ['upsertRecipeRating'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertRecipeRating>>, {recipeId: number;data: RatingCreate}> = (props) => {
          const {recipeId,data} = props ?? {};

          return  upsertRecipeRating(recipeId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertRecipeRatingMutationResult = NonNullable<Awaited<ReturnType<typeof upsertRecipeRating>>>
    export type UpsertRecipeRatingMutationBody = RatingCreate
    export type UpsertRecipeRatingMutationError = HTTPValidationError

    /**
 * @summary Upsert Rating
 */
export const useUpsertRecipeRating = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertRecipeRating>>, TError,{recipeId: number;data: RatingCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertRecipeRating>>,
        TError,
        {recipeId: number;data: RatingCreate},
        TContext
      > => {

      const mutationOptions = getUpsertRecipeRatingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Remove the current user's rating for a recipe.
 * @summary Delete Rating
 */
export const deleteRecipeRating = (
    recipeId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Recipe>(
      {url: `/api/v1/ratings/${recipeId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteRecipeRatingMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeRating>>, TError,{recipeId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeRating>>, TError,{recipeId: number}, TContext> => {

const mutationKey = ['deleteRecipeRating'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRecipeRating>>, {recipeId: number}> = (props) => {
          const {recipeId} = props ?? {};

          return  deleteRecipeRating(recipeId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRecipeRatingMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRecipeRating>>>
    
    export type DeleteRecipeRatingMutationError = HTTPValidationError

    /**
 * @summary Delete Rating
 */
export const useDeleteRecipeRating = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRecipeRating>>, TError,{recipeId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRecipeRating>>,
        TError,
        {recipeId: number},
        TContext
      > => {

      const mutationOptions = getDeleteRecipeRatingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Return the current user's rating for a recipe, or null if not rated.
 * @summary Get My Rating
 */
export const getMyRecipeRating = (
    recipeId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetMyRecipeRating200>(
      {url: `/api/v1/ratings/${recipeId}/my`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMyRecipeRatingQueryKey = (recipeId?: number,) => {
    return [
    `/api/v1/ratings/${recipeId}/my`
    ] as const;
    }

    
export const getGetMyRecipeRatingQueryOptions = <TData = Awaited<ReturnType<typeof getMyRecipeRating>>, TError = HTTPValidationError>(recipeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRecipeRating>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyRecipeRatingQueryKey(recipeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyRecipeRating>>> = ({ signal }) => getMyRecipeRating(recipeId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(recipeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyRecipeRating>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyRecipeRatingQueryResult = NonNullable<Awaited<ReturnType<typeof getMyRecipeRating>>>
export type GetMyRecipeRatingQueryError = HTTPValidationError


export function useGetMyRecipeRating<TData = Awaited<ReturnType<typeof getMyRecipeRating>>, TError = HTTPValidationError>(
 recipeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRecipeRating>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyRecipeRating>>,
          TError,
          Awaited<ReturnType<typeof getMyRecipeRating>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyRecipeRating<TData = Awaited<ReturnType<typeof getMyRecipeRating>>, TError = HTTPValidationError>(
 recipeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRecipeRating>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyRecipeRating>>,
          TError,
          Awaited<ReturnType<typeof getMyRecipeRating>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyRecipeRating<TData = Awaited<ReturnType<typeof getMyRecipeRating>>, TError = HTTPValidationError>(
 recipeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRecipeRating>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get My Rating
 */

export function useGetMyRecipeRating<TData = Awaited<ReturnType<typeof getMyRecipeRating>>, TError = HTTPValidationError>(
 recipeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRecipeRating>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyRecipeRatingQueryOptions(recipeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




