/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { BodyLoginUserGrantType } from './bodyLoginUserGrantType';
import type { BodyLoginUserClientId } from './bodyLoginUserClientId';
import type { BodyLoginUserClientSecret } from './bodyLoginUserClientSecret';

export interface BodyLoginUser {
  grant_type?: BodyLoginUserGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginUserClientId;
  client_secret?: BodyLoginUserClientSecret;
}
