/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */

export interface BodyUploadRecipeImagesApiV1RecipesRecipeIdImagePost {
  files: Blob[];
}
