/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { CheckResultStatus } from './checkResultStatus';
import type { CheckResultError } from './checkResultError';

export interface CheckResult {
  status: CheckResultStatus;
  latency_ms: number;
  critical: boolean;
  error?: CheckResultError;
}
