/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type CheckFavoritesParams = {
/**
 * Comma-separated recipe IDs to check. Up to 200 ids per request.
 * @maxLength 4000
 */
ids: string;
};
