/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type CheckFollowingParams = {
/**
 * Comma-separated user IDs to check (up to 200).
 * @maxLength 4000
 */
ids: string;
};
