/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type CheckResultStatus = typeof CheckResultStatus[keyof typeof CheckResultStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CheckResultStatus = {
  ok: 'ok',
  fail: 'fail',
} as const;
