/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { CommentReportItemReporterUsername } from './commentReportItemReporterUsername';

/**
 * A single report row (one reporter, one reason).
 */
export interface CommentReportItem {
  reporter_id: number;
  reporter_username?: CommentReportItemReporterUsername;
  reason: string;
  created_at: string;
}
