/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export interface CommentReportCreate {
  /**
   * @minLength 1
   * @maxLength 500
   */
  reason: string;
}
