/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { CommentCreateParentCommentId } from './commentCreateParentCommentId';

export interface CommentCreate {
  /**
   * @minLength 1
   * @maxLength 2000
   */
  content: string;
  parent_comment_id?: CommentCreateParentCommentId;
}
