/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { CommentResponseAuthorUsername } from './commentResponseAuthorUsername';
import type { CommentResponseAuthorAvatarUrl } from './commentResponseAuthorAvatarUrl';
import type { CommentResponseParentCommentId } from './commentResponseParentCommentId';

export interface CommentResponse {
  id: number;
  recipe_id: number;
  user_id: number;
  author_username?: CommentResponseAuthorUsername;
  author_avatar_url?: CommentResponseAuthorAvatarUrl;
  author_role?: string | null;
  parent_comment_id?: CommentResponseParentCommentId;
  content: string;
  is_deleted: boolean;
  created_at: string;
  updated_at: string;
  replies?: CommentResponse[];
}
