/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

/**
 * IDs (from the request) that the current user has favorited.

Returning the positive-match subset (instead of `{id: bool}`) keeps the
payload small for the common case where most recipes aren't favorited.
 */
export interface FavoritesCheckResponse {
  favorited_ids: number[];
}
