/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

/**
 * Subset of the requested IDs that the current user has favorited.
 */
export interface FavoritesCheckResponse {
  favorited_ids: number[];
}
