/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

/**
 * Subset of the requested user IDs that the current user follows.
 */
export interface FollowCheckResponse {
  following_ids: number[];
}
