/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { ForgotPasswordRequestCaptchaToken } from './forgotPasswordRequestCaptchaToken';

export interface ForgotPasswordRequest {
  email: string;
  captcha_token?: ForgotPasswordRequestCaptchaToken;
}
