/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type GetRecipeCategoriesParams = {
/**
 * Recipes per category
 * @minimum 2
 * @maximum 20
 */
limit_per?: number;
};
