/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { HealthReportStatus } from './healthReportStatus';
import type { HealthReportChecks } from './healthReportChecks';

export interface HealthReport {
  status: HealthReportStatus;
  checks: HealthReportChecks;
}
