/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type HealthReportStatus = typeof HealthReportStatus[keyof typeof HealthReportStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthReportStatus = {
  ok: 'ok',
  degraded: 'degraded',
  fail: 'fail',
} as const;
