/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

/**
 * Required when action is 'reject'
 */
export type ModerationActionRejectionReason = string | null;
