/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type ModerationActionAction = typeof ModerationActionAction[keyof typeof ModerationActionAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModerationActionAction = {
  approve: 'approve',
  reject: 'reject',
} as const;
