/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */

/**
 * Required when action is 'reject'
 */
export type ModerationActionRejectionReason = string | null;
