/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { ModerationActionAction } from './moderationActionAction';
import type { ModerationActionRejectionReason } from './moderationActionRejectionReason';

export interface ModerationAction {
  action: ModerationActionAction;
  /** Required when action is 'reject' */
  rejection_reason?: ModerationActionRejectionReason;
}
