/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { NotificationResponseRecipeId } from './notificationResponseRecipeId';
import type { NotificationResponseCommentId } from './notificationResponseCommentId';

export interface NotificationResponse {
  id: number;
  user_id: number;
  type: string;
  title: string;
  message: string;
  is_read: boolean;
  recipe_id?: NotificationResponseRecipeId;
  comment_id?: NotificationResponseCommentId;
  from_user_id?: number | null;
  created_at: string;
}
