/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export interface PasswordChange {
  /**
   * @minLength 1
   * @maxLength 128
   */
  old_password: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  new_password: string;
}
