/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { PublicUserResponseDisplayName } from './publicUserResponseDisplayName';
import type { PublicUserResponseAvatarUrl } from './publicUserResponseAvatarUrl';

export interface PublicUserResponse {
  id: number;
  username: string;
  display_name?: PublicUserResponseDisplayName;
  avatar_url?: PublicUserResponseAvatarUrl;
  role?: string;
  created_at: string;
  recipe_count?: number;
  followers_count?: number;
  is_following?: boolean;
}
