/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export interface RatingResponse {
  recipe_id: number;
  user_id: number;
  rating: number;
  created_at: string;
  updated_at: string;
}
