/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export interface RatingCreate {
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
}
