/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type ReadUserRecipesParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
