/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */

export type ReadRecipesApiV1RecipesGetParams = {
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Comma-separated ingredient to include
   */
  include_ingredients?: string | null;
  /**
   * Comma-separated ingredient to exclude
   */
  exclude_ingredients?: string | null;
};
