/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type ReadSimilarRecipesParams = {
/**
 * @minimum 1
 * @maximum 20
 */
limit?: number;
/**
 * Max distance to consider recipes similar
 * @minimum 0
 * @maximum 2
 */
threshold?: number;
};
