/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type ReadRecipesParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Comma-separated ingredients to include
 */
include_ingredients?: string | null;
/**
 * Comma-separated ingredients to exclude
 */
exclude_ingredients?: string | null;
/**
 * Min cooking time in minutes
 */
min_time?: number | null;
/**
 * Max cooking time in minutes
 */
max_time?: number | null;
/**
 * Comma-separated: easy,medium,hard
 */
difficulty?: string | null;
/**
 * Comma-separated cuisine values
 */
cuisine?: string | null;
/**
 * Filter by meal_type tag (e.g. soup, dessert)
 */
meal_type?: string | null;
/**
 * Only return recipes with at least one comment
 */
has_comments?: boolean;
/**
 * Sort order: newest (default, id DESC), popular (engagement score), top_rated (average_rating DESC), most_favorited (favorites_count DESC)
 * @pattern ^(newest|popular|top_rated|most_favorited)$
 */
sort?: string;
};
