/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { RecipeTitle } from './recipeTitle';
import type { RecipeInstructions } from './recipeInstructions';
import type { RecipeCookingTimeInMinutes } from './recipeCookingTimeInMinutes';
import type { RecipeDifficulty } from './recipeDifficulty';
import type { RecipeCuisine } from './recipeCuisine';
import type { Ingredient } from './ingredient';
import type { RecipeOwnerId } from './recipeOwnerId';
import type { RecipeOwnerUsername } from './recipeOwnerUsername';
import type { RecipeRejectionReason } from './recipeRejectionReason';

export interface Recipe {
  title?: RecipeTitle;
  instructions?: RecipeInstructions;
  cooking_time_in_minutes?: RecipeCookingTimeInMinutes;
  difficulty?: RecipeDifficulty;
  cuisine?: RecipeCuisine;
  id: number;
  /** @maxItems 100 */
  ingredients?: Ingredient[];
  /** @maxItems 10 */
  image_urls?: string[];
  thumbnail_urls?: string[];
  owner_id?: RecipeOwnerId;
  owner_username?: RecipeOwnerUsername;
  status?: string;
  rejection_reason?: RecipeRejectionReason;
  has_pending_draft?: boolean;
}
