/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */
import type { RecipeCreateCuisine } from "./recipeCreateCuisine";

export interface RecipeCreate {
  /**
   * @minLength 3
   * @maxLength 255
   */
  title: string;
  /** @maxLength 50000 */
  instructions: string;
  cooking_time_in_minutes?: number;
  /** @maxLength 50 */
  difficulty: string;
  cuisine?: RecipeCreateCuisine;
  /** @maxItems 100 */
  ingredients?: string[];
  image_urls?: string[];
}
