/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { RecipeTagsPublicVegetarian } from './recipeTagsPublicVegetarian';
import type { RecipeTagsPublicVegan } from './recipeTagsPublicVegan';
import type { RecipeTagsPublicGlutenFree } from './recipeTagsPublicGlutenFree';
import type { RecipeTagsPublicDairyFree } from './recipeTagsPublicDairyFree';
import type { RecipeTagsPublicMealType } from './recipeTagsPublicMealType';
import type { RecipeTagsPublicMainProtein } from './recipeTagsPublicMainProtein';
import type { RecipeTagsPublicCookingMethod } from './recipeTagsPublicCookingMethod';
import type { RecipeTagsPublicSpiceLevel } from './recipeTagsPublicSpiceLevel';
import type { RecipeTagsPublicOccasion } from './recipeTagsPublicOccasion';
import type { RecipeTagsPublicCostTier } from './recipeTagsPublicCostTier';
import type { RecipeTagsPublicTechniqueDifficulty } from './recipeTagsPublicTechniqueDifficulty';
import type { RecipeTagsPublicCulturalSubRegion } from './recipeTagsPublicCulturalSubRegion';

/**
 * Public-facing tag data returned in Recipe responses.

All fields are optional — NULL means tags haven't been generated yet
(background task pending or LLM classification failed).
 */
export interface RecipeTagsPublic {
  vegetarian?: RecipeTagsPublicVegetarian;
  vegan?: RecipeTagsPublicVegan;
  gluten_free?: RecipeTagsPublicGlutenFree;
  dairy_free?: RecipeTagsPublicDairyFree;
  meal_type?: RecipeTagsPublicMealType;
  main_protein?: RecipeTagsPublicMainProtein;
  allergens?: string[];
  cooking_method?: RecipeTagsPublicCookingMethod;
  spice_level?: RecipeTagsPublicSpiceLevel;
  occasion?: RecipeTagsPublicOccasion;
  cost_tier?: RecipeTagsPublicCostTier;
  technique_difficulty?: RecipeTagsPublicTechniqueDifficulty;
  cultural_sub_region?: RecipeTagsPublicCulturalSubRegion;
}
