/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { RecipeDraftResponseDescription } from './recipeDraftResponseDescription';
import type { RecipeDraftResponseCuisine } from './recipeDraftResponseCuisine';
import type { Ingredient } from './ingredient';
import type { RecipeDraftResponseRejectionReason } from './recipeDraftResponseRejectionReason';

export interface RecipeDraftResponse {
  id: number;
  recipe_id: number;
  author_id: number;
  title: string;
  description?: RecipeDraftResponseDescription;
  instructions: string;
  cooking_time_in_minutes: number;
  difficulty: string;
  cuisine?: RecipeDraftResponseCuisine;
  ingredients?: Ingredient[];
  status: string;
  rejection_reason?: RecipeDraftResponseRejectionReason;
  created_at: string;
}
