/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */
import type { RecipeTitle } from "./recipeTitle";
import type { RecipeInstructions } from "./recipeInstructions";
import type { RecipeCookingTimeInMinutes } from "./recipeCookingTimeInMinutes";
import type { RecipeDifficulty } from "./recipeDifficulty";
import type { RecipeCuisine } from "./recipeCuisine";
import type { Ingredient } from "./ingredient";

export interface Recipe {
  title?: RecipeTitle;
  instructions?: RecipeInstructions;
  cooking_time_in_minutes?: RecipeCookingTimeInMinutes;
  difficulty?: RecipeDifficulty;
  cuisine?: RecipeCuisine;
  id: number;
  /** @maxItems 100 */
  ingredients?: Ingredient[];
  /** @maxItems 10 */
  image_urls?: string[];
}
