/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */
import type { RecipeUpdateTitle } from "./recipeUpdateTitle";
import type { RecipeUpdateInstructions } from "./recipeUpdateInstructions";
import type { RecipeUpdateCookingTimeInMinutes } from "./recipeUpdateCookingTimeInMinutes";
import type { RecipeUpdateDifficulty } from "./recipeUpdateDifficulty";
import type { RecipeUpdateCuisine } from "./recipeUpdateCuisine";
import type { RecipeUpdateIngredients } from "./recipeUpdateIngredients";
import type { RecipeUpdateImageUrls } from "./recipeUpdateImageUrls";

export interface RecipeUpdate {
  title?: RecipeUpdateTitle;
  instructions?: RecipeUpdateInstructions;
  cooking_time_in_minutes?: RecipeUpdateCookingTimeInMinutes;
  difficulty?: RecipeUpdateDifficulty;
  cuisine?: RecipeUpdateCuisine;
  ingredients?: RecipeUpdateIngredients;
  image_urls?: RecipeUpdateImageUrls;
}
