/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */

export interface RecipeImageDelete {
  /**
   * @minLength 1
   * @maxLength 2083
   */
  image_url: string;
}
