/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */

export interface RootResponse {
  status: string;
  project_name: string;
  version: string;
  documentation_url: string;
}
