/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type SearchUsersParams = {
/**
 * Search by username
 * @minLength 1
 * @maxLength 100
 */
q: string;
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
