/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */

export type SearchRecipesApiV1RecipesSearchGetParams = {
  /**
   * Search query for recipes using vector search
   * @maxLength 200
   */
  q: string;
};
