/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type SearchRecipesParams = {
/**
 * Search query for recipes using vector search
 * @maxLength 200
 */
q: string;
/**
 * Comma-separated ingredients to include
 */
include_ingredients?: string | null;
/**
 * Comma-separated ingredients to exclude
 */
exclude_ingredients?: string | null;
/**
 * Min cooking time in minutes
 */
min_time?: number | null;
/**
 * Max cooking time in minutes
 */
max_time?: number | null;
/**
 * Comma-separated: easy,medium,hard
 */
difficulty?: string | null;
/**
 * Comma-separated cuisine values
 */
cuisine?: string | null;
/**
 * Sort order applied AFTER relevance filtering: 'newest' (default) keeps vector-distance order, 'popular' re-orders the result set by favorites_count.
 * @pattern ^(newest|popular)$
 */
sort?: string;
};
