/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export type SearchRecipesParams = {
/**
 * Search query for recipes using vector search
 * @maxLength 200
 */
q: string;
/**
 * Comma-separated ingredient to include
 */
include_ingredients?: string | null;
/**
 * Comma-separated ingredient to exclude
 */
exclude_ingredients?: string | null;
};
