/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */

export interface TokenPair {
  access_token: string;
  refresh_token: string;
  token_type?: string;
}
