/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { Recipe } from './recipe';
import type { RecipeDraftResponse } from './recipeDraftResponse';

export type UpdateRecipe200 = Recipe | RecipeDraftResponse;
