/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { UserUpdateRole } from './userUpdateRole';
import type { UserUpdateIsActive } from './userUpdateIsActive';

export interface UserUpdate {
  role?: UserUpdateRole;
  is_active?: UserUpdateIsActive;
}
