/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { UserSelfUpdateUsername } from './userSelfUpdateUsername';
import type { UserSelfUpdateDisplayName } from './userSelfUpdateDisplayName';
import type { UserSelfUpdateEmail } from './userSelfUpdateEmail';

export interface UserSelfUpdate {
  username?: UserSelfUpdateUsername;
  display_name?: UserSelfUpdateDisplayName;
  email?: UserSelfUpdateEmail;
}
