/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */
import type { UserCreateDisplayName } from './userCreateDisplayName';

export interface UserCreate {
  email: string;
  /**
   * @minLength 3
   * @maxLength 100
   */
  username: string;
  display_name?: UserCreateDisplayName;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
}
