/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 2.0.0
 */

export interface UserCreate {
  email: string;
  /**
   * @minLength 3
   * @maxLength 100
   */
  username: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
}
