/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Smart Recipes Finder
 * OpenAPI spec version: 1.1.0
 */
import type { ValidationErrorLocItem } from "./validationErrorLocItem";

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}
